### ISSUE TITLE
Confluence cloud error.

### ISSUE THREAD

**Issue by yevhen-korientsov** [matbrgz/confluence-outline-migration#2]
Hi,
We're using confluence cloud, tried to test migration and got this error:
 
```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:593:10)
    at Object.readFileSync (node:fs:469:35)
    at Object.load (/home/eugene/work/infra/confluence-outline-migration/src/state.js:9:25)
    at readBaseAndReturnNewObject (/home/eugene/work/infra/confluence-outline-migration/src/input.js:14:22)
    at Object.robot [as input] (/home/eugene/work/infra/confluence-outline-migration/src/input.js:9:23)
    at start (/home/eugene/work/infra/confluence-outline-migration/index.js:22:24)
    at Object.<anonymous> (/home/eugene/work/infra/confluence-outline-migration/index.js:46:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Node.js v18.16.0

Can you please also clarify what should be exactly set in variables:
                                                                                           
CONFLUENCE_URL
CONFLUENCE_SPACEURL

**Comment by yevhen-korientsov** [comment]
Also, seems JSON file should exist before starting this migration script?. I see some example in base/testing.json

**Comment by phy12321** [comment]
same problem, have you fixed ?

**Comment by Zlateshkin1337** [comment]
> Also, seems JSON file should exist before starting this migration script?. I see some example in base/testing.json

have you fixed this problem?

**Comment by matbrgz** [comment]
Hi,

Thanks for reporting this. It looks like the tool assumes a local JSON state file (e.g., something under `base/`) is present before running, which isn’t clearly documented yet. You’ll need to create or copy a JSON file (for example, `base/testing.json`) and point `CONFLUENCE_SPACEURL` to your Cloud space’s URL (e.g., `https://your-domain.atlassian.net/wiki/spaces/SPACEKEY`). In your `.env`, you should have:

```
CONFLUENCE_URL=https://your-domain.atlassian.net
CONFLUENCE_SPACEURL=https://your-domain.atlassian.net/wiki/spaces/SPACEKEY
CONFLUENCE_EMAIL=your-email@example.com
CONFLUENCE_PASSWORD=your-api-token-or-password
OUTLINE_API_KEY=your-outline-api-key
```

As for the `ERR_INVALID_ARG_TYPE` error, it means the script tried to read a state file but didn’t find a valid path. To fix it, copy one of the example JSON files from `base/` (e.g., `base/testing.json`) to a new `base/state.json` (or whatever name you prefer) and update the code/config to point to that file path.

I haven’t had a chance to fully test Confluence Cloud recently, so this functionality may need updates to handle link conversion and newer Confluence APIs. If you’d like to add support for Cloud-specific endpoints or improve the error handling around missing state files, please feel free to open a pull request—any contribution to enhance compatibility and documentation is very welcome!

Best regards,
Matheus
